# This file is unique to AWS CodeDeploy projects
# Please see the following URLs for more information on the syntax:
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure.html
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-server

version: 0.0

os: "linux"

hooks:
  #ApplicationStop:

  Install:
    - location: "pipeline/scripts/install_dependencies.sh"
      timeout: 300
      runas: root

  #ApplicationStart:
