# This file is unique to AWS CodeDeploy projects
# Please see the following URLs for more information on the syntax:
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure.html
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-server

version: 0.0

os: "linux"

hooks:
  ApplicationStop:
    - location: "stop_service.sh"
      timeout: 300
      runas: root

  Install:
    - location: "install_dependencies.sh"
      timeout: 300
      runas: root

  ApplicationStart:
    - location: "start_service.sh"
      timeout: 300
      runas: root
