# This file is unique to AWS CodeBuild projects
# Please see the following URL for more information on the syntax:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    commands:
      - pip3 install -r requirements.txt

  build:
    commands:
      - python3 -m pytest tests/
