name: "Run pytest Unit Tests, build Docker Container and push to Docker Hub"

on:
  push:
    branches:
      - "main"
      - "feature/**"

jobs:
  Unit-Tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2.4.2
      - name: "Install Python Dependencies"
        run: "pip3 install -r requirements.txt"
      - name: "Run Unit Tests"
        run: "python3 -m pytest tests/"

  Build-Push-Docker-Container:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Docker Setup QEMU"
        uses: docker/setup-qemu-action@v2.0.0
      - name: "Docker Setup Buildx"
        uses: docker/setup-buildx-action@v2.0.0
      - name: "Docker Login"
        uses: docker/login-action@v2.0.0
