name: "Run pytest Unit Tests"

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"

jobs:
  Run Python Unit Tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2.4.2
      - name: "Install Python Dependencies"
        run: "pip3 install -r requirements.txt"
