name: "Run pytest unit tests, Python PEP 8 linting and push Docker container to Docker Hub"

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"

jobs:
  Unit-Tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2.4.2
      - name: "Install Python Dependencies"
        run: "pip3 install -r requirements.txt"
      - name: "Run Unit Tests"
        run: "python3 -m pytest tests/"
